- id: zscaler-iac-scanner
  name: runs zscaler iac scanner
  description: Runs Zscaler IaC Scanner
  entry: zscaler-iac-scanner
  language: python
  types: [text]
  stages: [commit, push, manual] 
  pass_filenames: false